<a href="https://colab.research.google.com/github/Hacko97/Color-Flipper/blob/master/initial_submission.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import libraries
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

import tensorflow as tf
# This code was tested with TensorFlow v1.8
print("You have TensorFlow version", tf.__version__)

You have TensorFlow version 2.6.0


In [ ]:
# load datasets
train_lable_df = pd.read_csv('/content/drive/MyDrive/Data mining assignment/training_set_labels.csv',index_col="respondent_id")
train_feauture_df = pd.read_csv('/content/drive/MyDrive/Data mining assignment/training_set_features.csv',index_col="respondent_id")
test_feauture_df = pd.read_csv('/content/drive/MyDrive/Data mining assignment/test_set_features.csv',index_col="respondent_id")

In [ ]:
print(train_feauture_df.shape)
print(test_feauture_df.shape)

(26707, 35)

In [ ]:
train_feauture_df.drop(columns=['employment_occupation','employment_industry','hhs_geo_region'],inplace=True)
test_feauture_df.drop(columns=['employment_occupation','employment_industry','hhs_geo_region'],inplace=True)

In [ ]:
# get the percentage of missing data
percent_missing = train_feauture_df.isnull().sum() * 100 / len(train_feauture_df)
missing_value_df = pd.DataFrame({'percent_missing': percent_missing})

In [ ]:
missing_value_df

percent_missing
h1n1_concern                        0.344479
h1n1_knowledge                      0.434343
behavioral_antiviral_meds           0.265848
behavioral_avoidance                0.778822
behavioral_face_mask                0.071142
behavioral_wash_hands               0.157262
behavioral_large_gatherings         0.325757
behavioral_outside_home             0.307036
behavioral_touch_face               0.479275
doctor_recc_h1n1                    8.087767
doctor_recc_seasonal                8.087767
chronic_med_condition               3.635751
child_under_6_months                3.070356
health_worker                       3.010447
health_insurance                   45.957989
opinion_h1n1_vacc_effective         1.464036
opinion_h1n1_risk                   1.452803
opinion_h1n1_sick_from_vacc         1.479013
opinion_seas_vacc_effective         1.729884
opinion_seas_risk                   1.924589
opinion_seas_sick_from_vacc         2.010709
age_group                           0.000000
education                           5.268282
race                                0.000000
sex                                 0.000000
income_poverty                     16.561201
marital_status                      5.272026
rent_or_own                         7.645936
employment_status                   5.477965
census_msa                          0.000000
household_adults                    0.932340
household_children                  0.932340

In [ ]:
train_feauture_df.head(5)

h1n1_concern  ...  household_children
respondent_id                ...                    
0                       1.0  ...                 0.0
1                       3.0  ...                 0.0
2                       1.0  ...                 0.0
3                       1.0  ...                 0.0
4                       2.0  ...                 0.0

[5 rows x 32 columns]

In [ ]:
train_feauture_df.columns[22:36]

Index(['education', 'race', 'sex', 'income_poverty', 'marital_status',
       'rent_or_own', 'employment_status', 'census_msa', 'household_adults',
       'household_children'],
      dtype='object')

In [ ]:
X = train_feauture_df.iloc[:, :].values
X_test1 = test_feauture_df.iloc[:, :].values
y_h = train_lable_df.iloc[:,0 ].values
y_s = train_lable_df.iloc[:,-1 ].values

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer.fit(X[:,:])
X[:,:] = imputer.transform(X[:,:])

In [ ]:
y_h

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
imputer.fit(X_test1[:,:])
X_test1[:,:] = imputer.transform(X_test1[:,:])

In [ ]:
X_test1.shape

(26708, 32)

In [ ]:
X.shape

(26707, 32)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [20,21,22,23,24,25,26,27,28,29,30,33,34])], remainder='passthrough')
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [21,22,23,24,25,26,27,28,29])], remainder='passthrough')

# X = ct.fit_transform(X)
# X_test1 = ct.fit_transform(X_test1).toarray()
X = np.array(ct.fit_transform(X))
X_test1 = np.array(ct.fit_transform(X_test1))

In [ ]:
X.shape

(26707, 51)

In [ ]:
X_test1.shape

(26708, 51)

In [ ]:
from sklearn.linear_model import LogisticRegression
#Create a svm Classifier
clf_h = LogisticRegression() # Linear Kernel

#Train the model using the training sets
clf_h.fit(X, y_h)


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
clf_s = LogisticRegression()
clf_s.fit(X,y_s)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
y_pred_h = clf_h.predict_proba(X_test1)
y_pred_s = clf_s.predict_proba(X_test1)

In [ ]:
y_pred_h

array([[0.92067901, 0.07932099],
       [0.95456746, 0.04543254],
       [0.53475633, 0.46524367],
       ...,
       [0.86499422, 0.13500578],
       [0.94358237, 0.05641763],
       [0.4620445 , 0.5379555 ]])

In [ ]:
y_pred_s

array([[0.74240912, 0.25759088],
       [0.96140159, 0.03859841],
       [0.31270022, 0.68729978],
       ...,
       [0.79259948, 0.20740052],
       [0.62999794, 0.37000206],
       [0.46997016, 0.53002984]])

In [ ]:
y_preds = np.transpose(np.array([y_pred_h[:, 1], y_pred_s[:, 1]]))

In [ ]:
y_preds = pd.DataFrame(y_preds, columns = ['h1n1_vaccine', 'seasonal_vaccine'])

In [ ]:
y_preds.to_csv('initial_submission_2.csv')